export const CATEGORIAS_LOADING = 'CATEGORIAS_LOADING';
export const CATEGORIAS_ERROR = 'CATEGORIAS_ERROR';
export const CATEGORIAS_TRAER_TODAS = 'CATEGORIAS_TRAER_TODAS';

export const CONTACTO_LOADING = 'CONTACTO_LOADING';
export const CONTACTO_ERROR = 'CONTACTO_ERROR';
export const CONTACTO_TRAER_TODAS = 'CONTACTO_TRAER_TODAS';

export const OPERACIONES_LOADING = 'OPERACIONES_LOADING';
export const OPERACIONES_ERROR = 'OPERACIONES_ERROR';
export const OPERACIONES_TRAER_TODAS = 'OPERACIONES_TRAER_TODAS';

export const PARTIDOS_LOADING = 'PARTIDOS_LOADING';
export const PARTIDOS_ERROR = 'PARTIDOS_ERROR';
export const PARTIDOS_TRAER_TODOS = 'PARTIDOS_TRAER_TODOS';

export const INMUEBLE_LOADING = 'INMUEBLE_LOADING';
export const INMUEBLE_ERROR = 'INMUEBLE_ERROR';
export const INMUEBLE_TRAER_TODOS = 'INMUEBLE_TRAER_TODOS';
export const INMUEBLE_TRAER_UNO = 'INMUEBLE_TRAER_UNO';
export const INMUEBLE_TRAER_MAS = 'INMUEBLE_TRAER_MAS';
export const INMUEBLE_UPDATE_PAGINATION = 'INMUEBLE_UPDATE_PAGINATION';
export const INMUEBLE_ACTUALIZAR_FILTROS = 'INMUEBLE_ACTUALIZAR_FILTROS';
export const INMUEBLE_RESTABLECER_FILTROS = 'INMUEBLE_RESTABLECER_FILTROS';
