import BannerSeccion from "../../components/Banner/bannerSeccion"
import Encabezado from "../../components/encabezado"
import { useRouter } from 'next/router'
import SliderPropiedad from "../../components/Propiedades/SliderPropiedad";
import styled from "styled-components";
import DatosPrincipales from "../../components/Propiedades/DatosPrincipales";
import DescripcionPropiedad from "../../components/Propiedades/Descripcion";
import ServiciosPropiedad from "../../components/Propiedades/Servicios";
import SliderPropiedades from "../../components/SliderPropiedades/Slider";
import FormBusqueda from "../../components/FormBusqueda/form";
import Footer from '../../components/Footer/footer';
import TituloDestacado from "../../components/tituloDestacado";
import {useContext,useEffect} from 'react';
import { InmuebleContext } from "../../context/inmuebles/inmueblesContext";
import Spinner from "../../components/Spinner";

const Propiedad = (props) => {
  const router = useRouter();
  const {query:{propiedad}} = router;
  const {seleccionado,loading,error,traerInmueble} = useContext(InmuebleContext);

  useEffect(() => {
    traerInmueble(125);
  }, [])

  return (
    !seleccionado ? <Spinner/> :
    <>
      <Encabezado title="Rosetto Propiedades - Inicio" description="Generated by create next app"/>
      <BannerSeccion seccion="Detalle propiedad"/>
      <div className="container">
        <Main className="row">
          <div className="col-12 col-md-7">
            <TituloDestacado innerHtml={`${seleccionado.data.OPERACION} - ${seleccionado.data.PARTIDO} - ${seleccionado.data.BARRIO}`}/>
            <SliderPropiedad/>
          </div>
          <div className="col-12 col-md-5">
            <DatosPrincipales/>
          </div>
        </Main>
        <hr/>
        <DescripcionPropiedad/>
        <ServiciosPropiedad/>
      </div>
      <br/><hr/><br/>
      <SliderPropiedades/>
      <br/>
      <FormBusqueda/>
      <Footer/>
    </>
  );
}

const Main = styled.div`
  align-items: center;
  @media(max-width:768px){
    align-items: flex-start
  }
`;


export default Propiedad;
