import Encabezado from '../components/encabezado';
import Banner from '../components/Banner/banner';

export default function Home() {
  return (
    <>
      <Encabezado title="Rosetto Propiedades - Inicio" description="Generated by create next app"/>

      <Banner/>
      <div className="container">
        fhgvjbknlmñ
      </div>
    </>
  )
}
