import Encabezado from '../components/encabezado';
import Banner from '../components/Banner/banner';
import Categorias from '../components/Categorias/categorias';
import SliderPropiedades from '../components/SliderPropiedades/Slider';
import FormBusqueda from '../components/FormBusqueda/form';

export default function Home() {
  return (
    <>
      <Encabezado title="Rosetto Propiedades - Inicio" description="Generated by create next app"/>

      <Banner/>
      <div className="container my-5">
        <Categorias/>
      </div>
      <SliderPropiedades/>
      <br/>
      <FormBusqueda/>
      <br/><br/>
    </>
  )
}
