import Encabezado from '../components/encabezado'

export default function Home() {
  return (
    <div>
      <Encabezado title="Rosetto Propiedades - Propiedades" description="Generated by create next app"/>
    </div>
  )
}
